version: '3.1'

services:
  db:
    build: .
    ports:
      - "1434:1433"
    volumes:
      - test_vol:/var/opt/mssql
    environment:
      - MSSQL_SA_PASSWORD=Justin123%
      - ACCEPT_EULA=Y

volumes:
  test_vol:
